### ISSUE TITLE
Kombatant not working with magitek?

### ISSUE THREAD

**Issue by Kumicoo** [Fryheit/Kombatant#3]
It throws me a huge error. here is the pastebin.

Is this known? Does it not work with magitek?

https://pastebin.com/hk1RS2Aq

**Comment by Fryheit** [comment]
Greetings,

you are experiencing this error because you have not installed Kombatant in the expected directory `.\BotBases\Kombatant` but `BotBases\Kombatant-master`. Please rename the directory and restart RebornBuddy, which should fix your issue.

Please let me know if this does not work for you.

**Comment by Kumicoo** [comment]
It worked.
